name: CI - Build Backend

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: amigoscode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify directory structure
        run: ls -al ./fullstackproject/backend

      - name: Build and run with Maven
        working-directory: ./fullstackproject/backend
        run: mvn -ntp -B install
